name: Artifacts Example
#on:
#  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        run: echo "Building project..."
      - name: Save Build Artifact
        run: echo "Build Successful!" > build.log
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-log
      - name: Display Build Log
        run: cat build.log
