name: Event Type Check

#on:
#  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Check Event Type
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "This is a push event"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "This is a pull request event"
          else
            echo "This is a scheduled event"
          fi
