on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use GITHUB_TOKEN securely
        run: echo "Using GITHUB_TOKEN without exposing it!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
