jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use GITHUB_TOKEN
        run: echo "Token: ${{ secrets.GITHUB_TOKEN }}"
