name: CI Example
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: string  # Use 'string' instead of 'environment'
        description: 'Choose the environment'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}  # Set environment directly as a string
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install
      
      - name: Print environment
        shell: bash
        run: echo "Environment: ${{ github.event.inputs.environment }}"
